name: Deploy Spring Boot App to Aliyun Windows 2012

on:
  push:
    branches:
      - main  # Replace with your default branch name

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Maven Build
        run: mvn clean package -DskipTests

      - name: Deploy to Aliyun Windows 2012
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.ALIYUN_WINDOWS_HOST }}
          username: ${{ secrets.ALIYUN_WINDOWS_USERNAME }}
          password: ${{ secrets.ALIYUN_WINDOWS_PASSWORD }}
          port: ${{ secrets.ALIYUN_WINDOWS_PORT }}
          script: |
            scp -P ${{ secrets.ALIYUN_WINDOWS_PORT }} target/your-app.jar ${{ secrets.ALIYUN_WINDOWS_USERNAME }}@${{ secrets.ALIYUN_WINDOWS_HOST }}:${{ secrets.ALIYUN_WINDOWS_REMOTE_DIR }}
            # Add any additional commands to start or configure the application on the Windows server if needed.
